### ISSUE TITLE
Board Menu

### ISSUE THREAD

**Issue by EunAhChoi** [banksemi/lunch-waiting#23]
- [x] DB 구조 만들기
- [x] 글 올리기 기능
- [x] 올라온 글 볼 수 있는 기능
- [ ] 게시글 삭제 기능
- [ ] 덧글 보는 기능
- [ ] 댓글 추가 기능
- [ ] 댓글 삭제 기능

**Comment by banksemi** [comment]
Scrolling in 'Board Menu' does not work normally after merging branches.
There is a problem with the above 'Question UI' scrolling together.

**Comment by banksemi** [comment]
@EunAhChoi 

This branch has been merged.
Therefore, we need to create an issue for the comment function.
